### ISSUE TITLE
Minor: Compiling recent versions in Arduino IDE throws declaration warnings...

### ISSUE THREAD

**Issue by NeilMarley** [grblHAL/core#108]
Is seems that a few new variables/functions (Which I suspect are only relevant in some options/plug-ins) are throwing-up warnings on compilation that they declared but unused....

Compiler output:

......Documents\Arduino\libraries\grblHAL_Teensy4\src\driver.c: In function 'driver_delay_ms':
C:\Users\Neil\Documents\Arduino\libraries\grblHAL_Teensy4\src\driver.c:574:39: warning: implicit declaration of function 'state_get' [-Wimplicit-function-declaration]
                 grbl.on_execute_delay(state_get());
                                       ^
In file included from .....Documents\Arduino\libraries\grblHAL_Teensy4\src\driver.c:73:0:
....Documents\Arduino\libraries\grblHAL_Teensy4\src\driver.c: At top level:
....Documents\Arduino\libraries\grblHAL_Teensy4\src\grbl/motor_pins.h:696:13: warning: 'motor_iterator' defined but not used [-Wunused-function]
 static void motor_iterator (motor_iterator_callback_ptr callback)
             ^
....Documents\Arduino\libraries\grblHAL_Teensy4\src\ioports.c:37:42: warning: 'analog_n_in' defined but not used [-Wunused-variable]
 static uint_fast8_t aux_n_in, aux_n_out, analog_n_in, *in_map = NULL, *out_map = NULL;;

**Comment by terjeio** [comment]
Thanks, I'll fix this in the next commit.
