### ISSUE TITLE
No two Axis support?

### ISSUE THREAD

**Issue by farbefreak** [grblHAL/core#124]
Hello Guys, 

i compiled the grblHAL files with your supplied guide for a Arduino Due. 
I changed the *_map to reflect my pin connections and everything seems to work. (Exept for a different [Issue](https://github.com/grblHAL/SAM3X8E/issues/6))

However I cant get a two axis mode to work. 

There is a statement inside the grbl/config.h:
"Defines number of axes supported - minimum 3, maximum 6"
but a contradictory one below: (after the homing section regarding the single Axis Homing commands)
"If you have a two-axis machine, DON'T USE THIS. Instead, just alter the homing cycle for two-axes."

I defined 
HOMING_CYCLE_0 (X_AXIS_BIT|Y_AXIS_BIT)  // Move X,Y at the same time.
to get the machine homing on just x and Y with the first cycle. 

However it still tries to home Z. (which my machine does not have)

So I assume the grblHAL does not support 2 Axies machines? That would be quite sad as I would have liked to make faster engravings with the faster processor. 

Is there something I can do about this?

**Comment by terjeio** [comment]
> Is there something I can do about this?

Reset the settings with `$RST=*` (as most definititions are now default values for settings) or use the [new $-settings](https://github.com/grblHAL/core/wiki/Additional-or-extended-settings) $44-$46 for which axes to home - `$44=3` and `$45=0` in your case.

**Comment by farbefreak** [comment]
Thanks 
I will test that tomorrow

**Comment by farbefreak** [comment]
Thanks for your help, that worked perfectly!
