### ISSUE TITLE
Should I ask Jon Escombe dresco? My H750VBT6 will give an alarm 3 if it sends a reset during motion, and then die, no response, F4 won't, send a reset in idle state and won't die

### ISSUE THREAD

**Issue by hankecnc** [grblHAL/core#134]

**Comment by hankecnc** [comment]
Jon Escombe dresco, will your H743 reset during exercise and will it die?

**Comment by dresco** [comment]
Yes, sorry - was missing a call to Driver_IncTick() in the systick handler. I've just updated my master branch with the fix..

**Comment by hankecnc** [comment]
> Yes, sorry - was missing a call to Driver_IncTick() in the systick handler. I've just updated my master branch with the fix..

thanks, he's getting better
