### ISSUE TITLE
Compiling error, No such file or directory, Arduino Due

### ISSUE THREAD

**Issue by MrAntza99** [grblHAL/core#138]
Folder grblHAL_Due/src/grbl/.. is empty, so Arduino IDE cant build firmware
What files I should add there from core, or should I?

![image](https://user-images.githubusercontent.com/43236706/165782238-589bb036-2dd7-42e4-b203-6fdb7e38aa00.png)
![image](https://user-images.githubusercontent.com/43236706/165782288-a1bee44f-0f97-419a-a3e4-c46da6561be6.png)

**Comment by terjeio** [comment]
You have to [pull in the required submodules](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL#using-git-command-line).
