### ISSUE TITLE
Spindel Speed stimmt nicht

### ISSUE THREAD

**Issue by TOKENone7472** [grblHAL/core#141]
Habe das Problem das die Mittlere Spindelgeschwindigkeit nicht stimmt. Ich benutze STM32F446RE und Arduino Shield CNC PWM Signal über Z+. Mittlere Spindelgeschwindigkeit habe ich 1,98V, bei Max Drehzahl 3,29V. 
Die Mittlere Spindelgeschwindigkeit sollte doch ca. 1.65V betragen oder ?
Ich danke schon einmal für Tips und Feedback.

**Comment by terjeio** [comment]
[My 446 Nucleo board](https://github.com/terjeio/CNC_Breakout_Nucleo64) outputs spindle voltages that are spot on.
Which board map are you using?
Spindle settings?

![image](https://user-images.githubusercontent.com/20260062/168477377-4891b3ef-64df-4cd6-a686-a918c44f3bab.png)

**Comment by TOKENone7472** [comment]
![Unbenannt (2)](https://user-images.githubusercontent.com/70366486/168487642-cd12f334-a6b7-4231-8b49-ffdd35100b8c.png)
I have 24000 RPM
Spindle PWM frequency 400Hz

**Comment by terjeio** [comment]
> Signal über Z+

This is the default pin, D11?

I have verified the output on that pin with your settings, both with scope and multimeter.
Do you measure the voltage when the pin is not connected? Can you check with a scope?

**Comment by TOKENone7472** [comment]
problem found. It was my mistake, I built a voltage converter and made a mistake with the capacitor. Everything great now. Thank you for your help.
Greeting TOKEN_one
