### ISSUE TITLE
my_machine.h vs CMakeLists.txt

### ISSUE THREAD

**Issue by marshr32** [grblHAL/core#143]
I see there is an option to select which board to compile for in both these files.
Do they have to both be set manually? 
Or does my_machine.h set the same board to ON in CMakeLists?

It's just that there is only my_machine.h mentioned in the compiling instructions, not CmakeLists and I found only this setting by chance.

Many thanks :)

**Comment by terjeio** [comment]
_my_machine.h_ contains this note
```
/*
  my_machine.h - configuration for ESP32 processos

  NOTE: only in use if not compiling with cmake (idf.py)

  ...
```

and the [readme this](https://github.com/grblHAL/ESP32#changelognotes).

so it is normally not in use. I guess I should hint at that in the generic compiling instructions.

**Comment by terjeio** [comment]
In later versions my_machine.h is now used instead of CMakeLists.txt.
