### ISSUE TITLE
Dual axis distances

### ISSUE THREAD

**Issue by Lopezno68** [grblHAL/core#15]
Hello, i found  a small error in the file limits.c
I think, the correct code is:
       float fail_distance = (-settings.homing.dual_axis.fail_length_percent / 100.0f) * settings.axis[dual_motor_axis].max_travel;
        fail_distance = min(fail_distance, settings.homing.dual_axis.fail_distance_**max**);
        fail_distance = max(fail_distance, settings.homing.dual_axis.fail_distance_**min**);
Bye..

**Comment by terjeio** [comment]
Good catch - a mistake on my part from when I switched from #defines for min and max to $-settings. Thanks for reporting!

**Comment by terjeio** [comment]
Fix comitted.
