### ISSUE TITLE
hi,terjeio,Command "M3" without S parameter, the pin cannot be set to high level, is it illegal?

### ISSUE THREAD

**Issue by hankecnccc** [grblHAL/core#156]
hi, terjeio, I'm glad to find a cheap and easily available chip "STM32F401RCT6" in this age of chip shortage, I used it to make a GRBLHAL board for sale, I found in my tests that only send when powered "M3", without the "S" parameter value, will not make the "spindle start" pin set to a high level, that is, the spindle starts, because the default "S" value is 0 when powered on, but is this illegal? The "M3" command is only the spindle turn-on signal, and should not be affected by the "S" value. The spindle PWM will be affected by the "S" value.
Finally, I wish you a happy life! !

**Comment by hankecnccc** [comment]
While waiting for your reply, I saw the explanation of parameter 7

**Comment by hankecnccc** [comment]
While waiting for your reply, I saw the explanation of parameter 7

**Comment by terjeio** [comment]
Fixed in [version 20220703](https://github.com/grblHAL/core/blob/master/changelog.md).

**Comment by hankecnccc** [comment]
So, is the other question I reported also a bug?

**Comment by hankecnccc** [comment]
> Fixed in [version 20220703](https://github.com/grblHAL/core/blob/master/changelog.md).

You seem to be busy lately? Also, good news, there are many people in China who are interested in your grblhal and they have pre-ordered the grblhal stm32F4 board that I made
