### ISSUE TITLE
The question that has been bothering me for a long time, why is [CTRL+X] reset?

### ISSUE THREAD

**Issue by hankecnccc** [grblHAL/core#157]
Reset to "0x18", what does it have to do with [CTRL+X]? He seems to be a combination shortcut key? Is this a historical issue?

**Comment by terjeio** [comment]
Character code 0x18 is [ASCII function CAN](https://www.asciitable.com/) (cancel) and has keyboard shortcut CTRL+X. Its grblHAL function is based on the original Grbl specification. You can map to another character code [here](https://github.com/grblHAL/core/blob/32f905abb3f95af10771398697a2b349e57e28d5/grbl.h#L103).
