### ISSUE TITLE
How to define emergency stop pin? I saw "emergency stop" when translating ioSender

### ISSUE THREAD

**Issue by hankecnccc** [grblHAL/core#160]
I don't want to use the reset pin as an emergency stop pin. When the emergency stop pin is pressed, an alarm should be issued to let the host computer know

**Comment by terjeio** [comment]
> I don't want to use the reset pin as an emergency stop pin.

Which reset pin? The one that "hard" resets the MCU or the one that performs a "warm" reset controlled by code?

FYI grblHAL supports mapping the "warm" reset input to a estop function that is a little less harsh, some drivers supports that, e.g the [iMXRT1062](https://github.com/grblHAL/iMXRT1062/blob/7dd77b4d252bca63dd56756026decda8662614bb/grblHAL_Teensy4/src/my_machine.h#L80-L81). I guess I should implement the option to remap to all drivers...

> When the emergency stop pin is pressed, an alarm should be issued to let the host computer know

[An alarm will be raised](https://github.com/grblHAL/core/blob/0db09ab6e925842407585158c5937c3729f34059/motion_control.c#L1040-L1079) (3 or 6) when there is ongoing motion if the reset pin is routed to the warm reset function, if routed to the estop function an alarm (10) will always be raised.
