### ISSUE TITLE
SAM3X8E Ethernet 

### ISSUE THREAD

**Issue by MARIOBASZ** [grblHAL/core#170]
Is it possible to connect grblHal with the Arduino Due board via Ethernet, and improve electrical noise problems?
Ethernet is not in the SAM3X folder.
Is Bluetooth a good option for electrical noise?

**Comment by terjeio** [comment]
It should be posible provided somebody writes/debugs the neccesary driver code as I am not planning to do so. AFAIKT the Ethernet PHY pins are not brought out so not entirely easy? [A cloned board has](https://forum.arduino.cc/t/connecting-an-ethernet-phy-to-arduino-due/139492) and may be a better option? Or better switch to a more modern processor that already has ethernet support such as the [iMXRT1062](https://github.com/grblHAL/iMXRT1062) or [STM32H7Fxx](https://github.com/dresco/STM32H7xx) driver by @dresco?

> Is Bluetooth a good option for electrical noise?

If noise is a problem I would not go for radio-based communication.
