### ISSUE TITLE
use second uart

### ISSUE THREAD

**Issue by MARIOBASZ** [grblHAL/core#174]
I would like to be able to send current position data to a second microprocessor, (I don't know whether to receive information). Is it easy to do?

**Comment by terjeio** [comment]
Which driver?

**Comment by MARIOBASZ** [comment]
I am using Arduino Due.

**Comment by terjeio** [comment]
Ok, then the easiest is perhaps enabling MPG_MODE and parsing the data coming from the MPG port. If you are connecting via the programming port another option is to listen in on the TX pin. Both these methods requires a sender requesting a status report at regular intervals or a plugin triggering it when no sender is connected.

If you want your own format and automatic pushing of position data you can write [a plugin](https://github.com/grblHAL/Templates/tree/master/my_plugin) that [opens an UART stream](http://svn.io-engineering.com/grblHAL/html/stream_8h.html#a5fd022599405a1221dceac5559b96587) and outputs the data you need. You can use the tick timer (1ms interval) in combination with subscribing to the `on_execute_realtime` event. An example of how to produce a regular event is in [this plugin](https://github.com/grblHAL/Templates/tree/master/my_plugin/stm32F411blinky).
I do not have any straigth example code for how to open an UART - the closest ones are the [Bluetooth](https://github.com/grblHAL/Plugins_Bluetooth/blob/230a01864a5d8376f022888544ba05ac91475f90/hc_05.c#L312-L324) or [ModBus](https://github.com/grblHAL/Plugins_spindle/blob/a3450d236c09818e8fef1c25b9385683993f00a0/modbus.c#L497-L552) plugins.

**Comment by MARIOBASZ** [comment]
Is it okay to listen to Tx while connected to the computer? If it doesn't cause any inconvenience, I would start by trying that way.

**Comment by terjeio** [comment]
> Is it okay to listen to Tx while connected to the computer?

Yes, I have done so with other boards.

**Comment by MARIOBASZ** [comment]
Thanks. I'll try that way.
