### ISSUE TITLE
Use of the ODrive system with the grblHAL

### ISSUE THREAD

**Issue by Tettraspere** [grblHAL/core#175]
Hi to all!

I would like to know if it is possible to use the ODrive system with the grblHAL.

I am triyng to achive high speeds for long periods and i am worried about having issues with back EMF from the stepper motors.

Thanks.

**Comment by terjeio** [comment]
[This](https://odriverobotics.com/)? If so it has a step/dir interface sou can be used.

**Comment by Tettraspere** [comment]
I wasn't aware of this new board from them. The board that i had on my mind was the version 3.6, that received communication by the RX and TX signal.

I have to read a bit about this new board.

I was curious if someone had tried this hardware . It seems an interesting choise for very fast movements for a long period of time due to the way that it deals with the back EMF.

**Comment by hanke-cnc** [comment]
> [This](https://odriverobotics.com/)? If so it has a step/dir interface so can be used.



> [This](https://odriverobotics.com/)? If so it has a step/dir interface so can be used.

hi, terjeio, this looks very interesting, looks like it can be used to make cheap servo motors? Makes our CNC machines more powerful, so cool!
