### ISSUE TITLE
Can grblhal support encoder handwheels natively? Is it difficult to implement?

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#176]
I have used another stm32f1 chip to read the encoder handwheel through the <Plugin_keypad> plug-in and then send the serial port commands to grblhal. It works well. I don't know if it is possible to let grblhal handle the encoder by itself. How difficult is it to implement
![IMG_20220821_093749](https://user-images.githubusercontent.com/108179425/185771702-b229efa8-0ca9-43c6-b25b-cc40dcf8b86b.jpg)
?

**Comment by terjeio** [comment]
There is a [plugin for that](https://github.com/grblHAL/Plugin_encoder) - jogging is work in progresss and I would like input on that part.

Currently only the iMXRT1062 driver has the [driver level interface implemented](https://github.com/grblHAL/iMXRT1062/blob/722004542dd4b1158edf4c5cff8b1121f8ee5581/grblHAL_Teensy4/src/driver.c#L1855-L1905), how easy it will be to implement the interface for other MCUs depends on whether a quadrature encoder peripheral is present and can be used.

In the iMXRT1062 [driver.c](https://github.com/grblHAL/iMXRT1062/blob/master/grblHAL_Teensy4/src/driver.c) search for `QEI_ENABLE` to find the code blocks - and note that this code does not use a quadrature encoder peripheral for input,
