### ISSUE TITLE
main.c:30: undefined reference to `grbl_enter

### ISSUE THREAD

**Issue by duinzicht8** [grblHAL/core#178]
I have made a new directory "grblHAL_Due_Upload" and all source copied to that directory.
I compiled it with Arduino-IDE 1.8.19

Arduino: 1.8.19 (Linux), TD: 1.56, Board: "Arduino Due (Programming Port)"

sketch/main.c.o: In function `setup':
/home/jan/SAM3X8E/grblHAL_Due/src/grblHAL_Due_Upload/main.c:30: undefined reference to `grbl_enter'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Due (Programming Port).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by terjeio** [comment]
Follow [this procedure](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL) to get the sources and compile.
The [grblHAL_Due_Upload](https://github.com/grblHAL/SAM3X8E/tree/master/grblHAL_Due/examples/grblHAL_Due_Upload) folder should only contain the .ino file.

**Comment by duinzicht8** [comment]
Terjeio, thanks for your reply,

the Arduino due is working now, but how to activate the 4the and 5the axis.
If I use G1 A=6 in the gcode, there is an error.

**Comment by terjeio** [comment]
Number of axes is [defined here](https://github.com/grblHAL/core/blob/5dd9c3eb18b6a0757de65d3fa49912882489355b/config.h#L35-L41).

BTW `G1 A=6` is incorrect syntax, it should be `G1 A6` (and feedrate has to be set).
