### ISSUE TITLE
Teensy4.1 WebUI compile error

### ISSUE THREAD

**Issue by pzh11001** [grblHAL/core#182]
I use Arduino ide 1.8.19. The MCU is teensy4.1

Download the latest grblHAL version, install the sdcard plug-in, networking plug-in, and webui plug-in. 
In "my_ machine.h" , i opening "define ethernet_enable 1" and "define sdcard_enable 1" in the "my_ machine.h" file, it can compile successfully. And connect grblhal normally through Ethernet. I can use "wschat.html" . and the connection is successful and the command is sent normally .

However, when I open "define webui_enable 1" in "my_ machine.h" file, a compilation error occurred. As follows:
(I have patched all the plug-in according to the instructions, but it seems that there is a folder in "teensy41_ethernet master"library need to be deleted. I forget which folder it is.)

Error:
![image](https://user-images.githubusercontent.com/33888349/188304155-7e712525-ca23-4bce-b9db-c2be33432b17.png)
![image](https://user-images.githubusercontent.com/33888349/188304182-8a299d1c-49a0-43b9-ac87-2cdc8d6864f9.png)

After commenting out "/ / # define webui_enable 1",  it can compile normally, start wschat.html, connect normally, and send commands normally
![image](https://user-images.githubusercontent.com/33888349/188304464-04578756-4aac-4e31-861d-4636d70bfd4b.png)
![image](https://user-images.githubusercontent.com/33888349/188304510-fcf5c0c3-47b0-4106-9e42-5c8f0fb750d5.png)

**Comment by terjeio** [comment]
Another one forgotten...
Change `LWIP_HTTPD_CUSTOM_FILES` in the patched _lwipopts.h_ to
`#define LWIP_HTTPD_CUSTOM_FILES        0`

Be aware that the latest [WebUI build is currently not working](https://github.com/luc-github/ESP3D-WEBUI/tree/3.0/dist/CNC/GRBLHal), I am looking into that now.

**Comment by pzh11001** [comment]
I see, Thank you for your great work！
Don't be too tired：）

**Comment by terjeio** [comment]
FYI [WebUI v3 support is improving](https://github.com/grblHAL/core/blob/master/changelog.md), flash filing system added etc...
