### ISSUE TITLE
Paid development request

### ISSUE THREAD

**Issue by mac7988** [grblHAL/core#185]
I want to implement parallel delta kenamtics.
Of this is something you can do I am happy to pay for the development cost.

**Comment by terjeio** [comment]
I'll rather try to support you if you can write the transform code as I do not have a machine to test with.
grblHAL already has an[ abstraction layer](http://svn.io-engineering.com/grblHAL/html/structkinematics__t.html) for kinematics transforms so there is no need to modify the core (other than adding this as an option).

An example implementation that segments movements is the [wall plotter code](https://github.com/grblHAL/core/blob/master/wall_plotter.c), I guess the parallell delta kinematics implementation will have to do the same.

A quick search for parallell delta kinematics did not return much useful code/info, these may be useful:

A library for parallel delta kinematics -[ on github](https://github.com/byq77/DeltaKinematics).

[The delta parallel robot - pdf](https://www.ohio.edu/mechanical-faculty/williams/html/PDF/DeltaKin.pdf).
