### ISSUE TITLE
Proposal | Proposal: Should a wait delay time to implement spindle start should be added to the core? The user can set the time through $

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#202]
To be precise, it is proposed by the user who purchased the grblhal control board

**Comment by dresco** [comment]
Hi, there is already a spindle at speed check, see [this discussion](https://github.com/grblHAL/core/discussions/198) for recent explanation..

Btw, you may want to raise a PR to get your map file upstream?

**Comment by hanke-cnc** [comment]
> Hi, there is already a spindle at speed check, see [this discussion](https://github.com/grblHAL/core/discussions/198) for recent explanation..
> 
> Btw, you may want to raise a PR to get your map file upstream?

terjeio is a great man

**Comment by dresco** [comment]
> Do you mean to upload the pin definition file for the grblhal control board I sell?
> Oh, I made the PCB according to the cnc3040.map file in the stm32F4 driver file, so it is not necessary

Yes, that is what I meant.. Thanks.
