### ISSUE TITLE
GRBLHAL ofSTM32H7XX 

### ISSUE THREAD

**Issue by pzh11001** [grblHAL/core#218]
I used the high-performance teensy4.1 GRBLHAL. Very good performance, really great work.

STM32H7XX series SCM has a high cost performance ratio. Do you consider making a GRBLHAL for H7?

**Comment by dresco** [comment]
@pzh11001 there is a work in progress H7xx driver [here](https://github.com/dresco/STM32H7xx/).

**Comment by pzh11001** [comment]
> @pzh11001 there is a work in progress H7xx driver [here](https://github.com/dresco/STM32H7xx/).
Thanks！
