### ISSUE TITLE
Hello, terjeio, I seem to have found a small bug in grblhal? The S value of the gc status information is the last value, not the current value

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#219]
Hello, terjeio, I seem to have found a small bug in grblhal? The S value of the gc status information is the last value, not the current value

The F/S value obtained by ? is the correct value

![ggg](https://user-images.githubusercontent.com/108179425/200168620-30c06e26-98aa-42dc-bc0b-806a90967ec0.png)

**Comment by hanke-cnc** [comment]
I don't know if you can understand what I mean?

**Comment by terjeio** [comment]
> The S value of the gc status information is the last value, not the current value

Correct. The GC status is from the current parser state which is at the back of the planner queue, the ? report is the current value including any override. This is per design.

**Comment by hanke-cnc** [comment]
> > The S value of the gc status information is the last value, not the current value
> 
> Correct. The GC status is from the current parser state which is at the back of the planner queue, the ? report is the current value including any override. This is per design.

????????????
God, in my cognition, the gc state is the current state of grbl executing a line of g code

**Comment by hanke-cnc** [comment]
I don't know linuxcnc and fanuc are the same?

**Comment by hanke-cnc** [comment]
Now I don't know how to implement the idea of continuing processing after the user shuts down. Originally, my idea was to save the gc state of the currently executing G code line, send the saved gc state when continuing to process, and then send the g code from the specified line, but now Knowing that the gc state is not the current execution g-code state, does the great terjeio have any ideas?
