### ISSUE TITLE
How to turn off coolant and spindle (independently) while on feedhold?

### ISSUE THREAD

**Issue by karoria** [grblHAL/core#224]
Is there a way or realtime command in grblHAL for turning off coolant and spindle independently? What if accidently a cycle start is issued if spindle is off? Any safety algorithm is there like spindle turns on automatically and after some delay it resumes program?

**Comment by terjeio** [comment]
> Is there a way or realtime command in grblHAL for turning off coolant and spindle independently?

[Yes](https://github.com/grblHAL/core/blob/d10804433c2b1060bb8ad6c5fa04218c2cf435a8/grbl.h#L146-L148).

> What if accidently a cycle start is issued if spindle is off?

If stopped during a feed hold by the override command it will be restored, if not running prior to the cycle start it will remain not running.

>  Any safety algorithm is there like spindle turns on automatically and after some delay it resumes program?

Yes - spindle state should be restored on resume.

**Comment by karoria** [comment]
Thanks.
