### ISSUE TITLE
503 error when generating binaries on web builder

### ISSUE THREAD

**Issue by imechura** [grblHAL/core#234]
Whenever I attempt to generate a binary on the webbuilder for rPI pico I get an error 503.

**Comment by terjeio** [comment]
The docker image was not running, you can try again now.

**Comment by henryjliu** [comment]
This seems to be still broken.  I selecte Driver RP2040, Board BTT SKR Pico 1.0 and it gives me 503.  Others like STM32F1xx work fine

**Comment by terjeio** [comment]
The RP2040 docker instance was down for some reason, try again now.
