### ISSUE TITLE
GRBLHAL for STM32G0

### ISSUE THREAD

**Issue by forcegl** [grblHAL/core#235]
Hello.  I have a board from a Bigtreetech Manta M4P 3D printer on an STM32G0 microcontroller.  Do you consider making a GRBLHAL for G0?

**Comment by terjeio** [comment]
Currently I have no immediate plans for adding drivers for new MCUs.
You can do it?
A recent example of a third party driver is the [STM32H7xx driver](https://github.com/dresco/STM32H7xx) by @dresco. This shows it is possible for the community to add to the supported MCU list.
