### ISSUE TITLE
I want to add a custom system setting, such as $777, how should I do it?

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#251]
I want to add a custom system setting, such as $777, how should I do it?

**Comment by hanke-cnc** [comment]
I want to use this to configure the feedrate of the handwheel function I added to grblhal

**Comment by terjeio** [comment]
> how should I do it?

Like [this](https://github.com/grblHAL/Templates/blob/master/my_plugin/settings/my_plugin.c). There are [other templates](https://github.com/grblHAL/Templates/tree/master/my_plugin) and [plugins](https://github.com/grblHAL/plugins) that add settings too - so plenty of examples available.
