### ISSUE TITLE
HELP, Flashtool 3.4.2 not found at expressif site any more

### ISSUE THREAD

**Issue by Ams-Laser** [grblHAL/core#267]
Can someone please provide link for downloadtool, the lint at the compiling instructions point to expressif site and the tool is at difrent version now so i dont, know how to use the newone
Thanks
Ed

**Comment by terjeio** [comment]
The latest version works just fine, at least the Windows version. Here is how I set it up to flash a Web Builder build:

![image](https://user-images.githubusercontent.com/20260062/224790998-d94d1f0b-d411-4cee-921b-a24e2684ad3d.png)

**Comment by Ams-Laser** [comment]
Ok, it works just have to wayt for about 5 minutes before the actual download begins
