### ISSUE TITLE
Hi, I see that there is an automatic real-time report mode, where is it enabled? I did not find it in config.h

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#281]

**Comment by terjeio** [comment]
`$481` - [autoreport interval in ms](https://github.com/grblHAL/core/blob/d4f5b3b6643bde2457664ce4c3fe924331c44c87/config.h#L1692-L1699).

```
$$=481
Interval the real time report will be sent, set to 0 to disable.

NOTE: A hard reset of the controller is required after changing this setting.
```

**Comment by hanke-cnc** [comment]
酷!!!太棒了,我非常喜欢您的这个功能😍

**Comment by hanke-cnc** [comment]
Cool!!! That's great, I really like this feature of yours.

**Comment by hanke-cnc** [comment]
> `$481` - [autoreport interval in ms](https://github.com/grblHAL/core/blob/d4f5b3b6643bde2457664ce4c3fe924331c44c87/config.h#L1692-L1699).
> 
> ```
> $$=481
> Interval the real time report will be sent, set to 0 to disable.
> 
> NOTE: A hard reset of the controller is required after changing this setting.
> ```

Cool!!! That's great, I really like this feature of yours.
