### ISSUE TITLE
Minimum, Maximum Limit Switch and Home Origin Swatch support for each axis 

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [grblHAL/core#285]
Due to large number of pins on uC now a day, it's would be very much good to add support for positive, negative limit switches and origin sitch support for each axis. The new extended switch configuration or current single limit switch configuration can be selected via a `#define` macro as per ease of user

**Comment by terjeio** [comment]
This is already supported by the core - driver implementations has to be added.

See [here](https://github.com/grblHAL/core/blob/b6e43d6c194fa0f830ff3987a4aa1cd78b310dd6/nuts_bolts.h#L149-L155) and [here](https://github.com/grblHAL/core/blob/b6e43d6c194fa0f830ff3987a4aa1cd78b310dd6/grbllib.c#L238-L240).
