### ISSUE TITLE
Constant rotation of an axis by just providing RPM.

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [grblHAL/core#286]
I want to rotate `X-Axis` just like spindle. But I want to rotate it continuously with a commanded RPM.
`X10Y1Z4` means that rotate X with 10RPM , move Y to 1 and Z to 4. It would be nice if we can modify each axis. And synch the rpm with over all feed as well (Incase of feed override).

**Comment by terjeio** [comment]
This is not easy/possible to implement and is not supported by standard gcode semantics. What is the use case for this?

**Comment by LoganFraser** [comment]
Probably a stepper or servo driven lathe, given the context.

**Comment by terjeio** [comment]
Closed due to lack of feedback.

**Comment by MuhammadQaisarAli** [comment]
> This is not easy/possible to implement and is not supported by standard gcode semantics. What is the use case for this?

Yes you are right, we don't have standard g-code support and that's the challenge to be faced. A used case would be filament winding machine.

**Comment by MuhammadQaisarAli** [comment]
> Probably a stepper or servo driven lathe, given the context. 

Hmm.. that could be a possible option.

**Comment by MuhammadQaisarAli** [comment]
> A stepper driven spindle controlled by the S parameter is possible. Hijacking the X parameter and controlling it through the planner etc. is not something I would attempt to implement - that path is designed for synchronous motion.

Yes but that won't be an accurate solution, rather a go on
