### ISSUE TITLE
Negative position after homing

### ISSUE THREAD

**Issue by Demitrius** [grblHAL/core#289]
Hello

After homing LaserGRBL show negative position. How can I solve it?
![image](https://user-images.githubusercontent.com/2479194/232279877-d00e058b-3f51-4714-9de8-89717d1aa76d.png)

**Comment by terjeio** [comment]
Set `$22=9`. Send `$$=22` for more `$22` options.

**Comment by Demitrius** [comment]
Thank you so much! It works
