### ISSUE TITLE
Laser power allways near 100%

### ISSUE THREAD

**Issue by throbulator01** [grblHAL/core#314]
Trying to get grblhal working on an esp32 with lightburn. The pwm output at 1% laser power does about 3.2 volts which is way too high.  Ive tried fluid nc and that operates as expected. 

Machine settings: 

$$
$0=10.0
$1=25
$2=0
$3=0
$4=7
$5=0
$6=0
$9=1
$10=511
$11=0.010
$12=0.002
$13=0
$14=0
$15=0
$16=0
$17=0
$18=0
$19=0
$20=0
$21=0
$22=0
$23=0
$24=25.0
$25=500.0
$26=250
$27=1.000
$28=0.100
$29=0.0
$30=1000.000
$31=0.000
$32=1
$33=1000.0
$34=0.0
$35=0.0
$36=100.0
$37=0
$39=1
$40=0
$43=1
$44=4
$45=3
$46=0
$62=0
$63=3
$64=0
$65=0
$100=100.000
$101=100.000
$102=250.000
$110=10000.000
$111=10000.000
$112=500.000
$120=600.000
$121=600.000
$122=10.000
$130=200.000
$131=200.000
$132=200.000
$341=0
$342=30.0
$343=25.0
$344=200.0
$345=200.0
$346=1
$384=0
$398=35
$481=0

using the esp32 master driver im a little over my head in this whole thing. Im running an old nano shield with jumpers in the right slots. Everything ive researched indicates it should be correctly configured.

**Comment by terjeio** [comment]
Which board map? And which version (output from `$I`)?
My test board is working fine, even with 1000 Hz PWM ($30) which is, IMO, on the low end for lasers.

**Comment by throbulator01** [comment]
I set it to the bdring v4 map. Im really not sure what you mean by the $I output for the version sorry im not rly a programmer im just figuring it out as i go

**Comment by throbulator01** [comment]
omg nvm i made a mistake, i had enable laser and pwm control pins mixed up :/ user error sorry for the disruption. Thanks for your time!!!!
