### ISSUE TITLE
 "Differential signal?" Does it look cool? Can grblHAL have it? Just curious.

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#347]
I was just browsing the web and came across it, then got curious and asked you. You know more.
![QQ截图20230817222122](https://github.com/grblHAL/core/assets/108179425/d470408b-57db-4e05-aebe-a52dc24585fa)

**Comment by terjeio** [comment]
> Can grblHAL have it?

Yes, why not? You will need a board that has differential output drivers that converts the single ended signals from the MCU. The drivers can be on board the controller itself or on an external board.

**Comment by andrewmarles** [comment]
FWIW, FlexiHAL uses differential drivers for the stepper outputs, and also has provision to use the differential encoder input to transport input signals a long way (I have tested with 30m of cable).

**Comment by hanke-cnc** [comment]
> andrewmarles

Awesome, andrewmarles! I'll take a look and give your project a try when I have the time. Thank you so much
