### ISSUE TITLE
FeedRate and Jogging  causing unresponsive state

### ISSUE THREAD

**Issue by Jay-Tech** [grblHAL/core#349]
Having the FeedRate override  set to anything other then 100 percent will casue a unresponsive state when you try to   jog.  There is no movement or console ouput, have to reset to get  movement back.

Tryed on boards Nucloe-64-STM32F446 and Flexi-HAL with same results 
Not sure if this it the right place to put this  or a better place would be core ?

**Comment by Jay-Tech** [comment]
Thank you Terjeio, 
Issue is resolved for STM32F4xx driver

**Comment by terjeio** [comment]
Thanks for the feedback.
