### ISSUE TITLE
When automatic status reporting is enabled, you will not receive the HOME status.

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#361]
I speculate that manual reports were sent previously. If the user requests homing, it waits for the next one to arrive and sends a homing status, then homes again. No reports are sent during homing.

**Comment by terjeio** [comment]
Will fix in the next commit. At least one report will be sent before homing starts.

> No reports are sent during homing.

Correct, reporting is disabled.

**Comment by terjeio** [comment]
Fix commited.
