### ISSUE TITLE
cmake includes plugins by default

### ISSUE THREAD

**Issue by wiersmapa** [grblHAL/core#382]
Tried to build RP2040 from the git repository and ran into errors (for example in 'unused' trinomatic plugin.)  The CMakeLists.txt file has if(AddMyPlugin) with the list of plugins and and an else() which lists them all again.  I removed the unused plugins from that else() list and it compiled with no errors.

**Comment by terjeio** [comment]
Which errors? I do not get any.

**Comment by wiersmapa** [comment]
I pulled a new copy and this time it compiled without errors.  I remember a
number of errors related to the TRINOMATIC variable declarations (the
stream variables in tmc_uart.c) which made me think it was related to the
plugins.  Not sure what was different before.  Thanks, Paul

**Comment by terjeio** [comment]
Perhaps a bug in the previous version? I stumble across some now and then, mostly minor and annoying ones. Anyway, thanks for reporting.
