### ISSUE TITLE
How to hide littlefs from showing up in FTP  as well as files list

### ISSUE THREAD

**Issue by karoria** [grblHAL/core#397]
Hi @terjeio 
I liked the old behaviour of not showing up webui files in littlefs in either FTP/WebDAV or files list populated by "http://URL/upload?path=/" I want the users of machine don't delete the webUI files by mistake. I would like to use only "http://URL/?forcefallback=yes" for webUI file management in flash memory. This behaviour was there in old builds but updating to new build has made those files visible in all places.

**Comment by terjeio** [comment]
A new setting, $650, for filing system options will get a flag for "hiding" the littlefs mount when listing the contents of the root directory in the next core commit.

**Comment by karoria** [comment]
Thanks @terjeio 
I will be eagerly waiting for this new commit.

**Comment by terjeio** [comment]
It is [available now](https://github.com/grblHAL/core/blob/master/changelog.md#20231210).

**Comment by karoria** [comment]
Thanks @terjeio ...
