### ISSUE TITLE
Error Compiling for Teensy4.1

### ISSUE THREAD

**Issue by theomajigga** [grblHAL/core#4]
![image](https://user-images.githubusercontent.com/10425478/111406163-c2bcb080-869f-11eb-8d6a-66f910453e2a.png)

Can't get passed this error.

using latest arduino IDE, and full download from https://github.com/grblHAL/iMXRT1062

**Comment by terjeio** [comment]
Did you install [Teensyduino](https://www.pjrc.com/teensy/td_download.html)? It is [required](https://github.com/grblHAL/iMXRT1062).

**Comment by theomajigga** [comment]
Yes, same error

**Comment by terjeio** [comment]
Sorry, I did not see that you are compiling for the wrong board. You have to select Teensy 4.1 from _Tools > Board: ... > Teensyduino_. If you have already done that then there is something wrong with your installation as the missing file is part of Teensyduino.

**Comment by theomajigga** [comment]
Oh christ. What a noob mistake.

**Comment by theomajigga** [comment]
What do you know, it worked when I did it right.
