### ISSUE TITLE
Translate to English: Request for support of G2/G3 circular arcs with omitted output coordinates for such subsequent arcs.

### ISSUE THREAD

**Issue by hanke-cnc** [grblHAL/core#401]
Many users using GRBLHAL have reported errors with circular arcs. Upon inspecting their G-code, I had to explain to them that the CAM post-processor they were using omits the coordinates for the subsequent arc in the output. Advising users to switch post-processors has proven somewhat challenging, as most CAM post-processors for Fanuc that I found online tend to omit this output as well.

G3 X30. Y0.0 R5.
G2 I-30.
G3 X32.7 Y-4.44 R5.

**Comment by terjeio** [comment]
The base specification for grblHAL is NIST RS274NGC v3. Core extensions mainly follows the LinuxCNC specification.
I see that NIST and LinuxCNC differs slightly in how (full circle) arcs are handled and that the [LinuxCNC specification](http://linuxcnc.org/docs/html/gcode/g-code.html#gcode:g2-g3) might be closer to the Fanuc spec. This means that a change to be compliant with the LinuxCNC specification may well lead to Fanuc style arcs become valid. However, to validate such a change I need some Fanuc style files for testing. Do you have some?

**Comment by hanke-cnc** [comment]
[fanuc_arc.txt](https://github.com/grblHAL/core/files/13574454/fanuc_arc.txt)
![b](https://github.com/grblHAL/core/assets/108179425/330b22d6-a2b8-42bb-9932-5bc1d2e038d6)
![a](https://github.com/grblHAL/core/assets/108179425/ee82e4a4-c086-4bdf-9dd1-3b82c917bd1c)

**Comment by hanke-cnc** [comment]
[cs.txt](https://github.com/grblHAL/core/files/13574851/cs.txt)
![b](https://github.com/grblHAL/core
![bb](https://github.com/grblHAL/core/assets/108179425/906c77b4-1231-448c-bbee-1aa89bd6cb0b)
/assets/108179425/f8b8c0ff-5338-4a10-81b2-ed888579f49b)

**Comment by hanke-cnc** [comment]
![c](https://github.com/grblHAL/core/assets/108179425/a609a163-e351-4fb9-bc82-321fa61eb674)

**Comment by terjeio** [comment]
Seems like I can update arc handling to match. However there are some other commands that errors out, `O0001` and `G05.1 Q0`.

**Comment by hanke-cnc** [comment]
> Seems like I can update arc handling to match. However there are some other commands that errors out, `O0001` and `G05.1 Q0`.

Okay, it doesn't matter for O0001 and G05.1 Q0, it's irrelevant

**Comment by terjeio** [comment]
Here is a modified _gcode.c_ for you to test with, most likely it will only compile with the latest core:

[gcode.zip](https://github.com/grblHAL/core/files/13692906/gcode.zip)

I am not able to find good enough documentation to match the gcode against the LinuxCNC specfication and I am unsure if any sideeffects will show up.
_cs.txt_ is an odd file, for me it seems the gcode implicitly swithes from radius mode to center mode arcs - and there are lines with only a single ijk word... Anyway both examples run to completion when I remove unsupported commands.

**Comment by hanke-cnc** [comment]
> Here is a modified _gcode.c_ for you to test with, most likely it will only compile with the latest core:
> 
> [gcode.zip](https://github.com/grblHAL/core/files/13692906/gcode.zip)
> 
> I am not able to find good enough documentation to match the gcode against the LinuxCNC specfication and I am unsure if any sideeffects will show up. _cs.txt_ is an odd file, for me it seems the gcode implicitly switches from radius mode to center mode arcs - and there are lines with only a single ijk word... Anyway both examples run to completion when I remove unsupported commands.

Okay, okay, I will test it.
