### ISSUE TITLE
Can’t write firmware to MKS Tinybee v1.0 

### ISSUE THREAD

**Issue by Davinjw** [grblHAL/core#421]
Can’t seem to get firmware installed. Getting a “no xmc flash detected”error

any ideas?
Thanks in advance!

![image](https://github.com/grblHAL/core/assets/155922432/c87e15c5-60ac-462b-9ab7-1be1a87e5695)

**Comment by Davinjw** [comment]
Disregard/delete. I didn’t check the boxes on the left -facepalm-

**Comment by grzesiekn** [comment]
Hi, I can flash the board using files from web builder, but after connecting via putty I get gibberish. I am using 115200 8N1.

**Comment by terjeio** [comment]
@grzesiekn This works for me (with a dev board):

[firmware.zip](https://github.com/grblHAL/core/files/14151923/firmware.zip)

![image](https://github.com/grblHAL/core/assets/20260062/78a1c395-0419-4b93-810b-7791abfebb4a)

**Comment by grzesiekn** [comment]
It works, thank you.
