### ISSUE TITLE
Compilation error: Inc/driver.h:688:5: error: unknown type name 'pin_cap_t'

### ISSUE THREAD

**Issue by PecaJosef** [grblHAL/core#454]
I am trying to compile the newest version but I am getting this error.

**Comment by terjeio** [comment]
Which driver?

**Comment by PecaJosef** [comment]
STM32F446. I have built a custom board and previous versions compiled successfully but didn't work as expected so I tried the new one but got this error.

**Comment by terjeio** [comment]
Ok, it looks like your [submodules are out of sync](https://github.com/grblHAL/core/wiki/Compiling-grblHAL#using-git-command-line). Check the core [build date](https://github.com/grblHAL/core/blob/06f442643a115ab3acd6722b4afc1fcee8d9d7be/grbl.h#L45) against your copy.

**Comment by PecaJosef** [comment]
Yeah it was a problem on my side, thank you for your help.
