### ISSUE TITLE
Qestion about min/max values

### ISSUE THREAD

**Issue by shaise** [grblHAL/core#458]
Hi @terjeio 

I'm in a process now to adapt my sender to use your internal parameter definition report instead of a fixed one. Thanks for this great feature!
I have a question though about parameter 481: autoreport.
the default value is 0, (disable) but the min/max allowed values are 100 to 1000. This causes an issue in my implementation as I do not allow values lower then min, hence I can not disable autoreport unless I do a special 'if' for this parameter.

what do you suggest? How do you handle it?
Thanks!

shai

**Comment by terjeio** [comment]
There is a flag at the end of the settings report which you can check - if 1 blank (for strings) or 0 is allowed for the setting.
```
[SETTING:481|1|Autoreport interval|ms|5|###0|100|1000|1|1]
                                                        ^
```

**Comment by shaise** [comment]
Ahhh! NICE!!!

Thanks!

**Comment by shaise** [comment]
Thanks again!
Works great now.
![image](https://github.com/grblHAL/core/assets/5813568/22cac786-4e96-4288-a3c3-70fc5c036bfb)

**Comment by shaise** [comment]
Closing
