### ISSUE TITLE
No reset in alarm?

### ISSUE THREAD

**Issue by Schildkroet** [grblHAL/core#461]
Hello,
 after first power up, i get following message:
```
GrblHAL 1.1f ['$' or '$HELP' for help]
ALARM:10
[MSG:Emergency stop - clear, then reset to continue]
```

In this state, it seems a reset (0x18) is not possible/ignored. But why?

**Comment by hanke-cnc** [comment]
"Have you started trying GRBLHAL yet? I am using your candle2, it is excellent."

IMPORTANT! grblHAL defaults to normally closed (NC) switches for inputs, if none are connected when testing it is likely that the controller will start in alarm mode.
Temporarily short the Reset, E-Stop and Safety Door4 inputs to ground or invert the corresponding inputs by setting $14=73 to avoid that.

**Comment by terjeio** [comment]
> But why?

Basic safety - it is a bad idea to bypass the reset/estop beeing asserted, if there is a button on the machine it will no longer work (until deasserted/released).  More in the [Wiki](https://github.com/grblHAL/core/wiki/First-Run-Grbl-Settings).
