### ISSUE TITLE
spindle_add_null does not fill .esp32_off which leads to crash

### ISSUE THREAD

**Issue by Nick507** [grblHAL/core#473]
Function spindle_add_null (spindle_control.c:437) does not fill optional pointer esp32_off in spindle_ptrs_t structure.
As result, spindle_all_off() crashes.
Most likely, this is a case when spindle init failed by some reason.

**Comment by terjeio** [comment]
I keep forgetting about the lurking ESP32 guru... Will fix in the next commit.
