### ISSUE TITLE
ioport_settings_load bug in out ports

### ISSUE THREAD

**Issue by Nick507** [grblHAL/core#476]
ioports.c:721

`        if((xbar = hal.port.get_pin_info(Port_Digital, Port_Output, ioports_map_reverse(digital.in.ports, --port)))) {`

I think that digital.in.ports must be changed to digital.**out**.ports, because as I understand in this (second) section we are handling out ports.
I've got crash when configured no input aux port, and one output.

**Comment by terjeio** [comment]
Thanks, will fix in the next commit.
