### ISSUE TITLE
MKS Tinybee  cannot connect to the router using STA

### ISSUE THREAD

**Issue by lnjzghy** [grblHAL/core#490]
Hello everyone,

**_**I have an ESP32 board, MKS Tinybee V1.0, and I want to build a Delta Robot. I generated firmware using the grblHAL Web Builder, using release version 20240408. In the Network/WebUI options card, I enabled V2+V3, Telnet Server, WebSocket, and HTTP server. The WIFI MODE is set to AP+STA, but I cannot connect to the router using STA. It seems that DHCP is not enabled. I tried $RST=*, but after restarting the board, DHCP still won't start. I also tried connecting with a fixed IP address, setting the address to 192.168.9.200, gateway to 192.168.9.1, and subnet mask to 255.255.255.0, but I cannot find where to input DNS. This is the information displayed in the terminal after inputting $I,**_** 
       >>> $I
[VER:1.1f.20240402:]
[OPT:VNMSL,100,1024,3,0]
[AXS:3:XYZ]
[NEWOPT:ENUMS,RT+,HOME,ES,REBOOT,SED,RTC,WIFI,SD]
[FIRMWARE:grblHAL]
[SIGNALS:HSEP]
[NVS STORAGE:*FLASH]
[FREE MEMORY:168K]
[DRIVER:ESP32]
[DRIVER VERSION:240330]
[DRIVER OPTIONS:4.3.2]
[BOARD:MKS Tinybee V1.0]
[AUX IO:1,0,0,0]
[WIFI MAC:08:d1:f9:4d:95:40]
[IP:192.168.5.1]
[PLUGIN:WebUI v0.21]
[KINEMATICS:Delta v0.04]
[PLUGIN:SDCARD v1.13]
[PLUGIN:FS macro plugin v0.07]
ok
**_and this is the configuration information in IOsender. What am I doing wrong? Please correct me. Thank you very much for your help, and I apologize for taking up your time. My English is not good, so thanks to chatGPT for the translation. Once again, thank you for helping me!_**
![IOsender](https://github.com/grblHAL/core/assets/28078472/a3bc3281-4803-4697-8fac-c763ba8c546c)
![WEBbulid](https://github.com/grblHAL/core/assets/28078472/eeff93bd-acc0-4fde-af4d-334aecbe9439)

**Comment by terjeio** [comment]
Try changing $73 to 1 (Station) and reboot the controller.

**Comment by lnjzghy** [comment]
@terjeio  
_He's working, thank you for your help, thanks.
Please help to complete the last part of the rotary DELTA. 
Thank you for your time, and please accept my sincere gratitude._

**Comment by terjeio** [comment]
> Please help to complete the last part of the rotary DELTA.

Which part is that? Something [related to this issue](https://github.com/grblHAL/core/issues/346)?
And please open a new issue for it as this has been resolved.
