### ISSUE TITLE
STATE_ALARM:10 sets STATE_ESTOP

### ISSUE THREAD

**Issue by 5ocworkshop** [grblHAL/core#51]
Working through my alarm indicator code, I discovered that the reset/e-stop button escaped my handler and then I realized that while the e-stop is state_alarm:10 (as showin in IOSender), it actually sets STATE_ESTOP.

I was just curious what the thinking is behind having both STATE_ALARM:10 and STATE_ESTOP?

**Comment by terjeio** [comment]
IIRC it is a safety feature, legacy Grbl is, IMO, a bit sloppy regarding that allowing clearing of alarms even when the underlying condition is not cleared. STATE_ESTOP is a grblHAL extension and as long as the estop input is asserted it is not possible to clear it. It is an optional feature and requires driver support, typically the reset input is reassigned as the estop input. Handling of a estop condition is also a little less hard than reset condition.
