### ISSUE TITLE
Web Builder is not available in China

### ISSUE THREAD

**Issue by zhuyuwu110** [grblHAL/core#533]
Web Builder is not available in China
![微信截图_20240615005040](https://github.com/grblHAL/core/assets/158246784/ff8b7a6b-ed1c-4d2a-a90c-2ee682a08b57)

**Comment by terjeio** [comment]
I do not provide a chinese version - either this is some rogue site or a bad (automatic?) translation.

**Comment by zhuyuwu110** [comment]
![微信截图_20240615101930](https://github.com/grblHAL/core/assets/158246784/d0cb6644-883e-4547-92fa-25cc55521d2f)
![微信截图_20240615101954](https://github.com/grblHAL/core/assets/158246784/0815eeb9-2c22-429f-8004-6d1303e13198)

**Comment by zhuyuwu110** [comment]
![微信截图_20240615101930](https://github.com/grblHAL/core/assets/158246784/8b80dbc2-6086-40ef-9e4e-b7dbe170d80a)
