### ISSUE TITLE
When homing is ongoing real-time report requests are ignored？

### ISSUE THREAD

**Issue by attying** [grblHAL/core#551]
hello terjeio，I found that sending '?' does not receive any response When homing is ongoing. This is somewhat different from FluidNC. Can real-time reporting be enabled, or where should I modify it in the source code?

**Comment by terjeio** [comment]
> I found that sending '?' does not receive any response When homing is ongoing.

Correct, this is how legacy grbl behaves.

> Can real-time reporting be enabled, or where should I modify it in the source code?

[It can](https://github.com/grblHAL/core/blob/8b9b7859ee6b370442d380d3d754fa5392b064b2/machine_limits.c#L216-L245) but should it? Any reason for why?

**Comment by attying** [comment]
I am glad to receive your prompt reply. I hope to observe the changes in the machine position during the process of returning home, which can be useful in certain situations. For example, during debugging or when the machine travel is relatively large. FluidNC and Mach3 are like this, can you tell me where to enable or modify them? I really need it, thank you!

**Comment by attying** [comment]
i 'm sorry! I didn't notice your mark. The problem has been resolved, thank you very much for your answer!
