### ISSUE TITLE
Unexpected application of offset to macro parameters?

### ISSUE THREAD

**Issue by skasti** [grblHAL/core#594]
Not sure if this is a bug or a misunderstanding by me;

I have a macro that uses the tool probe to check if a tool is present in the spindle;
```gcode
(debug,#<_call_level>: Check if tool present)
o50 if [EXISTS[#<_scnc_config>]]
o50 else
    G65P100
    G65P101
o50 endif

(debug,X#24 Y#25 Z#26)
#<end_x> = #24
#<end_y> = #25
#<end_z> = #26

; Do stuff

G53 G1 Z[#<_scnc_clear_height>] F[#<_scnc_move_feed>]
G1 X[#<end_x>] Y[#<end_y>]
G1 Z[#<end_z>]

; #5070 is 1 or 0 depending on whether or not G38.3 & .5 was successfull
O10 return #5070
```

This macro is supposed to take X,Y,Z for where to return to after probing, but when I run it, the end-positions get the work offset applied.
Example (G54 is X-189.481 Y-84.047 Z-102.291):
```
G65 P302 Q1 X0 Y0 Z0
[MSG:2: Check if tool present]
[MSG:X-189.481 Y-84.047 Z-102.291]

G65 P302 Q1 X0 Y0 Z10
[MSG:2: Check if tool present]
[MSG:X-189.481 Y-84.047 Z-92.291]
```

From what I can gather, this happens because offsets are applied to `gc_block.values.xyz` (gcode.c@L2388 for me) before the parameters are copied to the macro context (gcode.c@L2443-2469 for me).

I have not looked into a possible solution, as I am not sure how to change this without probably breaking something else 😅 
Also, the reason I say I think it might also be a misunderstanding, is that I am not sure if I am supposed to use XYZ-etc as parameters to macros 🤔

**Comment by terjeio** [comment]
It is an oversight by me, try with adding this code [here](https://github.com/grblHAL/core/blob/323dd84b7972c6acab745faa6add0f32da91d2b6/gcode.c#L1759) as a quick fix:
```
    if(word_bit.modal_group.G0 && gc_block.non_modal_command == NonModal_MacroCall)
        axis_words.mask = ijk_words.mask = 0;
```
