### ISSUE TITLE
Spindle is switched off when speed is 0

### ISSUE THREAD

**Issue by Deltaplc** [grblHAL/core#617]
Good morning
Sorry for my english....google translator....
I wanted to replace an Arduino Mega (grbl) with an Arduino Due SAM3X8E (grblhal) to control a laser and have more computing power!
I noticed that the enable pin doesn't work like in grbl! M3 S0 = enable pin off!! But it remains active even with just M3!!
Can its behavior be modified so that it is compatible with the behavior of the old grbl? I'm sorry to bother you but I can't find any documentation about it!!
Thank you in advance!

**Comment by terjeio** [comment]
[Duplicate](https://github.com/grblHAL/SAM3X8E/issues/28), closed.
