### ISSUE TITLE
Possibility to impose a speed different from the maximum speed of the translation movement in G0 movements

### ISSUE THREAD

**Issue by Deltaplc** [grblHAL/core#620]
Good morning
I apologize for the inconvenience
I use ligtburn to drive a laser where I installed your grblhal.
To move (for example) from the starting point to the engraving area, use the G0 command,
given that in my case I use a very high max travel speed,
I wanted to know if it was possible to set a value for the movements in G0 mode other than the max travel value of the axes?
Maybe even default to the entire firmware.... or it would be great if you could add a $ setting to do this!
Thanks for the help

**Comment by terjeio** [comment]
See this [issue](https://github.com/grblHAL/SAM3X8E/issues/30).
