### ISSUE TITLE
Building firmware for RP2040 fails

### ISSUE THREAD

**Issue by ahmadmadary** [grblHAL/core#632]
Hi

I tried to build firmware for RP2040 board but it always fails (build failed:  503). what can be the cause of it?

<img width="542" alt="fail" src="https://github.com/user-attachments/assets/a6ca238a-b38a-4659-ac09-4390881f681d">

**Comment by terjeio** [comment]
The backend was down, restarted now.

**Comment by jattie-ire** [comment]
I have the same error again, unable to build and Pico configs.

**Comment by terjeio** [comment]
backend down again... up now.
