### ISSUE TITLE
M64/M65 executed immediately when parsed, not planned

### ISSUE THREAD

**Issue by skasti** [grblHAL/core#633]
I use M64/M65 to control an airblast that clears away chips from to tool rack/probe etc. Initially, I just added a short snippet of g-code wherever I wanted a blast;
```gcode
M64 P1
G4 S0.5
M65 P1
```

It turned out, though, that the `M64 P1`was executed when the line was parsed (well before moving to the place it was meant to airblast). Since the following line is a dwell, the digital output remained `on` until the machine moved to the correct position and the dwell completed. onyl then did it execute the `G65 P1`.

For me, this seems a bit unpredictable, and I would have expected M64/M65 to work similar to how G4 is only executed once the machine has reached the same place in the code.

My workaround is to do a short dwell before, but to me this feels like a band-aid. But maybe this is just how M64/M65 is supposed to work? 😕

**Comment by terjeio** [comment]
[This helps](https://www.linuxcnc.org/docs/html/gcode/m-code.html#mcode:m62-m65)?

**Comment by skasti** [comment]
Haha, of course I skipped right over the part that explains _exactly_ why it does this when I was reading about it 🙈 🤦
