### ISSUE TITLE
Dealing with unused pins

### ISSUE THREAD

**Issue by Cluelessamigoss** [grblHAL/core#641]
Greetings. I'm designing basic breakout board for BlackPill Alt. 2 STM32F411, using Web Builder to generate firmware. I don't plan to use UART, USB, spindle encoder and door\i2cstrobe pins and there is no option to disable them in Web Builder. Which of these pins can be left floating unconnected and which need pull-up or pull-down if left unused?

**Comment by terjeio** [comment]
See [AN4488](https://www.st.com/resource/en/application_note/an4488-getting-started-with-stm32f4xxxx-mcu-hardware-development-stmicroelectronics.pdf) - section 4.3.1. Currently unused pins are left in their default state.

**Comment by Cluelessamigoss** [comment]
Thank you!

**Comment by Cluelessamigoss** [comment]
Thanks!
