### ISSUE TITLE
Rpm report problem

### ISSUE THREAD

**Issue by MARIOBASZ** [grblHAL/core#71]
real-time report FS delivers a maximum value of 1000 for rpm (on the other hand, when the information is in F and S mode it is the correct value) I am interested in being able to add a field in the GUI (currently bCNC) to display the rpm while the machine is working. Can you correct this? Thanks,  hugs.

**Comment by terjeio** [comment]
The max spindle speed reported (and PWM output) is capped by the $30 setting. which defaults to 1000. Have you increased this to match your spindle max RPM?

**Comment by MARIOBASZ** [comment]
He did not know. I will modify it when it is in front of my pc. Thanks.
