### ISSUE TITLE
Different pwm pin for laser and spindle

### ISSUE THREAD

**Issue by MeKeCNC** [grblHAL/core#91]
Is it possible to have 2 different pwm pin for spindle and laser triggered by the $32 variable? I would like to have both spindle and laser mounted on machine at the same time without any firmware update.
as previously discussed here https://github.com/fra589/grbl-Mega-5X/issues/112

**Comment by terjeio** [comment]
Yes - but you have to add driver support or a driver specific plugin for it. With the [Huanyang spindle plugin](https://github.com/grblHAL/Plugins_spindle/blob/fee15a1b86c5527bfc43acdb2f8d0bc6231f9705/huanyang.c#L325-L360) it is already in place.

**Comment by MeKeCNC** [comment]
my expectation is , if $32 is activated then laser pwm pin will be triggered (via M3 Sxxx and M5) otherwise spindle pwm pin will be triggered

**Comment by terjeio** [comment]
Yes - that is what is the code linked above does. It checks the $32 setting for laser mode and switches the spindle accordingly.

**Comment by MeKeCNC** [comment]
I want to use different pwm pins, BESC spindle and pwm laser with fysetc e4 board, does this board support the plugging you mentioned?

**Comment by terjeio** [comment]
No, a board specific plugin or driver code has to be written for that.

**Comment by terjeio** [comment]
In later versions of the core it is possible for plugin/board support code to [register additional spindles](http://svn.io-engineering.com/grblHAL/html/spindle__control_8h.html#a7ad081a6d642d08e7a340c7ecc4ca92b). These spindles can then be selected with $32. The [spindle plugin](https://github.com/grblHAL/Plugins_spindle/) also add M104 for selecting which spindle to use without changing the $32 setting.
